# Generated by Django 6.0.3 on 2026-03-13 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('date_disposed', models.DateTimeField(auto_now_add=True)),
                ('disposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
